version: 2.0

jobs:
  ubuntu2004:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run: apt update && DEBIAN_FRONTEND=noninteractive apt -y install git gcc clang cmake libgcrypt20-dev libgtk-3-dev libgpgme-dev
      - run: chmod +x .ci/install_gtkcrypto.sh && .ci/install_gtkcrypto.sh

  ubuntuLatestRolling:
    docker:
      - image: ubuntu:rolling
    steps:
      - checkout
      - run: apt update && DEBIAN_FRONTEND=noninteractive apt -y install git gcc clang cmake libgcrypt20-dev libgtk-3-dev libgpgme-dev
      - run: chmod +x .ci/install_gtkcrypto.sh && .ci/install_gtkcrypto.sh

  debianLatestStable:
    docker:
      - image: debian:latest
    steps:
      - checkout
      - run: apt update && apt -y install git gcc clang cmake libgcrypt20-dev libgtk-3-dev libgpgme-dev
      - run: chmod +x .ci/install_gtkcrypto.sh && .ci/install_gtkcrypto.sh

  fedoraLatestStable:
    docker:
      - image: fedora:latest
    steps:
      - checkout
      - run: dnf -y update && dnf -y install git gcc clang cmake make libgcrypt-devel gtk3-devel gpgme-devel
      - run: chmod +x .ci/install_gtkcrypto.sh && .ci/install_gtkcrypto.sh

  archlinux:
    docker:
      - image: archlinux:latest
    steps:
      - checkout
      - run: pacman -Syu --noconfirm && pacman -S --noconfirm pkg-config git gtk3 libgcrypt gcc clang cmake make gpgme
      - run: chmod +x .ci/install_gtkcrypto.sh && .ci/install_gtkcrypto.sh

workflows:
  version: 2
  build:
    jobs:
      - ubuntu2004
      - ubuntuLatestRolling
      - debianLatestStable
      - fedoraLatestStable
      - archlinux
